name: CI
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  pure-go:
    name: Pure Go Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-go@v5
        with:
          go-version: '1.22'
      
      - name: Test pure Go implementation
        run: go test ./port -v
        
      - name: Build examples
        run: |
          go build ./...
          go vet ./...

  oracle-macos:
    name: Oracle Tests (macOS)
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
          
      - name: Install Clipper2
        run: brew install clipper2
        
      - uses: actions/setup-go@v5
        with:
          go-version: '1.22'
          
      - name: Test with CGO oracle
        run: go test ./... -tags=clipper_cgo -v

  oracle-linux:
    name: Oracle Tests (Linux)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
          
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential cmake pkg-config
          
      - name: Build Clipper2 from source
        run: |
          cd third_party/clipper2
          mkdir -p build && cd build
          cmake .. -DCMAKE_BUILD_TYPE=Release -DCLIPPER2_EXAMPLES=OFF -DCLIPPER2_TESTS=OFF
          make -j$(nproc)
          sudo make install
          sudo ldconfig
          
      - name: Create pkg-config file
        run: |
          sudo mkdir -p /usr/local/lib/pkgconfig
          cat > clipper2.pc << EOF
          prefix=/usr/local
          exec_prefix=\${prefix}
          libdir=\${exec_prefix}/lib
          includedir=\${prefix}/include
          
          Name: Clipper2
          Description: Polygon clipping and offsetting library
          Version: 1.5.4
          Libs: -L\${libdir} -lClipper2
          Cflags: -I\${includedir}
          EOF
          sudo cp clipper2.pc /usr/local/lib/pkgconfig/
          
      - uses: actions/setup-go@v5
        with:
          go-version: '1.22'
          
      - name: Test with CGO oracle
        run: |
          export PKG_CONFIG_PATH=/usr/local/lib/pkgconfig:$PKG_CONFIG_PATH
          go test ./... -tags=clipper_cgo -v

  # Future: Add Windows job with MSVC or MinGW build